# 2025-09-24

## numpy

#### numpy 라이브러리 pip install 과 import

In [ ]:
!pip install numpy

In [4]:
import numpy as np

In [16]:
np.__version__

'2.3.3'

<hr>

### 일반 list와 numpy array의 리스트 연산 수행속도 비교

##### %timeit
##### 해당 명령어가 수행되는 시간을 측정하는 매직명령어

In [20]:
%timeit L2 = [i**2 for i in range(1000)]

69.8 μs ± 13.8 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [24]:
arr = np.arange(1000)

%timeit arr2 = arr**2

1.31 μs ± 146 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


### 데이터 타입별 np.array 선언과 dtype 옵션, nan값

In [37]:
alist = [1, 2, 3, 4, 5, 6]
alist2 = [1.1, 2.2, 3.3, 4.4]
alist3 = [1, 2, 3, None, 5, 6]
alist3_nan = [1, 2, 3, np.nan, 5, 6]
alist4 = [1, 2, 3., 4]

ar1 = np.array(alist)
ar2 = np.array(alist2)
ar3 = np.array(alist3)
ar3_nan = np.array(alist3_nan)
ar4 = np.array(alist4)
ar4_int = np.array(alist4, dtype='int')

# int 배열
print(ar1)
print(type(ar1))
print(ar1.dtype)
print()

# float 배열
print(ar2)
print(type(ar2))
print(ar2.dtype)
print()

# None값 포함 배열
print(ar3)
print(type(ar3))
print(ar3.dtype)
print()

# np.nan값 포함 배열
print(ar3_nan)
print(type(ar3_nan))
print(ar3_nan.dtype)
print()

# int + float 배열
print(ar4)
print(type(ar4))
print(ar4.dtype)
print()

# int + float 배열을 dtype='int' 로 선언
print(ar4_int)
print(type(ar4_int))
print(ar4_int.dtype)
print()

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64

[1.1 2.2 3.3 4.4]
<class 'numpy.ndarray'>
float64

[1 2 3 None 5 6]
<class 'numpy.ndarray'>
object

[ 1.  2.  3. nan  5.  6.]
<class 'numpy.ndarray'>
float64

[1. 2. 3. 4.]
<class 'numpy.ndarray'>
float64

[1 2 3 4]
<class 'numpy.ndarray'>
int64



### np.array의 차원 표현과 reshape

In [51]:
arr1 = np.array([1, 2, 3, 4])
print(arr1)
print(arr1.ndim)
print(arr1.shape)
print()

arr2 = np.array([[1, 2, 3, 4]])
print(arr2)
print(arr2.ndim)
print(arr2.shape)
print()

arr3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)
print()

arr4 = arr3.reshape(-1,3)
print(arr4)
print(arr4.ndim)
print(arr4.shape)
print()

# 갯수가 12개인것을 7열로 만들어달라고 하면 못한다고 에러남
# arr5 = arr3.reshape(-1, 7)

arr6 = arr3.reshape(2, -1, 3)
print(arr6)
print(arr6.ndim)
print(arr6.shape)
print()

[1 2 3 4]
1
(4,)

[[1 2 3 4]]
2
(1, 4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2
(3, 4)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2
(4, 3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)



### np.array의 연산

In [61]:
alist = np.array([1, 2, 3, 4, 5])
blist = np.array([6, 7, 8, 9, 10])
clist = np.array([6, 7, 8, 9])
dlist = np.array([6, 7, 8, 9, np.nan])

print(alist + blist)
print(alist - blist)
print(alist * blist)
print(alist / blist)
print()

# 원소 수가 맞지 않을 경우 에러
# print(alist + clist)
# print(alist - clist)
# print(alist * clist)
# print(alist / clist)
# print()

print(alist + dlist)
print(alist - dlist)
print(alist * dlist)
print(alist / dlist)
print()

print(alist + 2)
print(alist - 2)
print(alist * 2)
print(alist / 2)
print()

[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]

[ 7.  9. 11. 13. nan]
[-5. -5. -5. -5. nan]
[ 6. 14. 24. 36. nan]
[0.16666667 0.28571429 0.375      0.44444444        nan]

[3 4 5 6 7]
[-1  0  1  2  3]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]



### 미션 - numpy array 연산 예제

In [62]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])


print(2*a+b)
print(a==2)
print(b>10)
print((a==2)&(b>10))


[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


##### * 팁 * 여기서 논리연산을 묶을때 and 가 아닌 & 를 이용했는데, 
##### and는 일반적인 값들(scalar) 에 대한 논리연산의 연산만 가능하고, 배열의 논리연산은 불가능해서
##### 벡터라이즈 연산인 & 을 이용해서 논리연산을 연산해야함

<hr>

### np.array 인덱싱, 슬라이싱 실습

##### 일반 리스트 인덱싱, 슬라이싱

In [66]:
alist = [[0, 1, 2], [3, 4, 5]]

print(alist[0][0], alist[0][1], alist[1][2])

0 1 5


In [85]:
alist = [[0, 1, 2], [3, 4, 5]]

print(alist[0][:2], alist[1][1:], [alist[0][1], alist[1][1]])

[0, 1] [4, 5] [1, 4]


##### np.array 인덱싱, 슬라이싱

In [89]:
alist = [[0, 1, 2], [3, 4, 5]]
np_alist = np.array(alist)

print(np_alist[0][0], np_alist[0][1], np_alist[1][2])
print(np_alist[0, 0], np_alist[0, 1], np_alist[1, 2])

0 1 5
0 1 5


In [93]:
alist = [[0, 1, 2], [3, 4, 5]]
np_alist = np.array(alist)

print(np_alist[0, :2], np_alist[1, 1:], np_alist[:, 1])
print(np_alist[[0, 1], [1, 1]])

[0 1] [4 5] [1 4]
[1 4]


In [102]:
alist = [[0, 1, 2], [3, 4, 5]]
np_alist = np.array(alist)
blist = [[0, 1, 2, 3], [4, 5, 6, 7]]
np_blist = np.array(blist)

print(np_alist[0, :3])
print(np_blist[:, 1])
print(np_blist[1, 1:])
print(np_blist[:2, :2])

[0 1 2]
[1 5]
[5 6 7]
[[0 1]
 [4 5]]


### 미션 - numpy array 슬라이싱 예제

In [118]:
np_clist = np.array([x for x in range(12)]).reshape(3, 4)

print(np_clist)
print()
print(np_clist[:2, :2])
print()
print(np_clist[1:3, 1:3])
print()
print(np_clist[-2:, -3:])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[0 1]
 [4 5]]

[[ 5  6]
 [ 9 10]]

[[ 5  6  7]
 [ 9 10 11]]


### 팬시 인덱싱 - 특정 인덱스에 해당하는 원소만 추출 (규칙성 없는 인덱싱, 슬라이싱에 유용)

##### boolean으로 표현하거나, 정수로 직접 지정 가능

In [120]:
a = np.array([x for x in range(10)])
idx = np.array([True, False, True, False, True, False, True, False, True, False])
idx2 = [0, 2, 5]

print(a)
print(a[idx])
print(a[idx2])

[0 1 2 3 4 5 6 7 8 9]
[0 2 4 6 8]
[0 2 5]


##### 정수로 직접 지정
##### 인덱스 자체도 배열로 [0, 1, 2], [1, 2, 0] 이렇게 지정해서 각각의 요소를 배열로서 표현해서 지정도 가능

In [127]:
b = np.array([x for x in range(1, 10)]).reshape(-1, 3)

print(b)
print()
print(b[[0, 2]])
print()
print(b[[0, 1, 2],[1, 2 ,0]])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [7 8 9]]

[2 6 7]


##### 해당 배열의 논리연산 결과값을 이용한 팬시인덱싱

In [133]:
arr = np.array([x for x in range(1, 9)])

print(arr % 2 == 0)
print(arr[arr % 2 == 0])

[False  True False  True False  True False  True]
[2 4 6 8]


In [136]:
arr = np.array([x for x in range(10)])

print(arr[arr % 2 == 1])

[1 3 5 7 9]


##### 팬시인덱싱에서 갯수가 안맞는 경우, 특정 인덱스만 계속해서 참조하는 경우

In [144]:
arr = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
idx = [0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 1 ,1 ,1, 1]

print(arr[idx])
print(arr[[0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 1, 1 ,1 ,1, 1]])

# boolean 인덱싱의 갯수가 모자르거나 많을 경우 에러. 아까 위의 arr % 2 == 0 처럼 전체 크기에 해당하는 boolean indexing 추천
# print(arr[[True, False, False]])

[11 11 11 11 11 11 33 33 33 33 33 22 22 22 22 22]
[11 11 11 11 11 11 33 33 33 33 33 22 22 22 22 22]


### 미션 - 팬시인덱싱 예제

In [141]:
arr = np.array([x for x in range(1, 13)]).reshape(3, -1)

print(arr)
print()
print(arr[:, [True, False, False, True]])
print()
print(arr[:,[0, 3]])
print()
print(arr[[2, 0, 1],:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 1  4]
 [ 5  8]
 [ 9 12]]

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
data = np.array([x**2 for x in range(1, 5)])

print(data)
print()

data_sqrt = np.sqrt(data)
data_exp = np.exp(data)
data_sum = np.sum(data)
data_mean = np.mean(data)
data_var = np.var(data)
data_std = np.std(data)

print(f'data 배열의 제곱근(루트)값 : {data_sqrt}')
print(f'data 배열의 지수함수(e의 지수승)값 : {data_exp}')
print(f'data 배열의 합값 : {data_sum}')
print(f'data 배열의 평균값 : {data_mean}')
print(f'data 배열의 분산값 : {data_var}')
print(f'data 배열의 표준편차값 : {data_std}')


[ 1  4  9 16]

data 배열의 제곱근(루트)값 : [1. 2. 3. 4.]
data 배열의 지수함수값 : [2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
data 배열의 합값 : 30
data 배열의 평균값 : 7.5
data 배열의 분산값 : 32.25
data 배열의 표준편차값 : 5.678908345800274


### 점심 전 실습 미션

In [167]:
x = np.array([x for x in range(1, 21)]).reshape(2, -1)

print(x[x % 3 == 0])
print(x[x % 4 == 1])
print(x[(x % 3 == 0) & (x % 4 == 1)])

[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]


<hr>

## pandas

#### pandas 라이브러리 pip install 과 import

In [ ]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
pd.__version__

'2.3.2'

##### csv 불러오기

In [18]:
df = pd.read_csv('data\heroes.csv')

# 실수 표현 방식을 e+10 의 지수표현 말고 일반 소수표현으로 바꾸는 코드 + 자릿수 콤마 구별
pd.options.display.float_format = '{:,.0f}'.format

df

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

<hr>

## ** 데이터 확인 3종세트 - info(), describe(), head() (중요) **

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      int64  
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      int64  
 5   재산      5 non-null      float64
dtypes: float64(1), int64(2), object(3)
memory usage: 468.0+ bytes


In [16]:
df.describe()

나이   키                 재산
count   7   7                  5
mean   34 190  2,300,278,000,120
std    13  36  5,142,800,956,894
min    18 170                600
25%    26 172         50,000,000
50%    32 177        340,000,000
75%    39 184      1,000,000,000
max    58 270 11,500,000,000,000

In [17]:
df.head()

이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000

<hr>

### dataframe의 type, unique, value_count

In [ ]:
print(df['국적'])
print(type(df['국적']))
print()
print(df['국적'].unique())
print()
print(df['국적'].value_counts())
print()

0       미국
1    아스가르드
2       미국
3    데미스키라
4       미국
5       미국
6      러시아
Name: 국적, dtype: object
<class 'pandas.core.series.Series'>

['미국' '아스가르드' '데미스키라' '러시아']

국적
미국       4
아스가르드    1
데미스키라    1
러시아      1
Name: count, dtype: int64


### dataframe의 nlargest

In [32]:
print(df['나이'].nlargest()) # default 로 5개 출력
print()
print(df['나이'].nlargest(7))
print()
print(df['키'].nlargest())
print()
print(df.nlargest(7, '키'))

0    58
1    45
4    33
6    32
3    27
Name: 나이, dtype: int64

0    58
1    45
4    33
6    32
3    27
5    25
2    18
Name: 나이, dtype: int64

4    270
1    190
3    178
2    177
0    174
Name: 키, dtype: int64

      이름  나이     직업     국적    키                 재산
4     헐크  33  핵물리학자     미국  270      1,000,000,000
1     토르  45      신  아스가르드  190                NaN
3   원더우먼  27     공주  데미스키라  178                NaN
2  스파이더맨  18   고등학생     미국  177                600
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000


### dataframe의 슬라이싱

In [34]:
print(df['이름'][:4])
print()
print(df[:3])

0     아이언맨
1       토르
2    스파이더맨
3     원더우먼
Name: 이름, dtype: object

      이름  나이    직업     국적    키                 재산
0   아이언맨  58   CEO     미국  174 11,500,000,000,000
1     토르  45     신  아스가르드  190                NaN
2  스파이더맨  18  고등학생     미국  177                600


### dataframe의 iloc, loc

##### df.iloc[행번호, 열번호]

In [49]:
print(df.iloc[1:4][:])
print()

# 밑은 위와 같음
print(df.iloc[1:4, :])
print()

print(df.iloc[[1, 3, 6]][:])
print()

print(df.iloc[:5, :3])

      이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

      이름  나이    직업     국적    키  재산
1     토르  45     신  아스가르드  190 NaN
2  스파이더맨  18  고등학생     미국  177 600
3   원더우먼  27    공주  데미스키라  178 NaN

      이름  나이   직업     국적    키         재산
1     토르  45    신  아스가르드  190        NaN
3   원더우먼  27   공주  데미스키라  178        NaN
6  블랙위도우  32  스파이    러시아  170 50,000,000

      이름  나이     직업
0   아이언맨  58    CEO
1     토르  45      신
2  스파이더맨  18   고등학생
3   원더우먼  27     공주
4     헐크  33  핵물리학자


##### df.loc['인덱스명', '컬럼명']

##### loc의 경우에는 이름 기반이기 때문에 loc[2:5] 이렇게 표현하더라도 '2에서부터 5까지' 를 포함해서 (즉 end값까지 포함해서) 출력함

In [55]:
# int 기반이라 end값 미포함
print(df.iloc[2:5])
print()

# 이름 기반이라 end값 포함
print(df.loc[2:5])

      이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000

      이름  나이     직업     국적    키            재산
2  스파이더맨  18   고등학생     미국  177           600
3   원더우먼  27     공주  데미스키라  178           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
5   캡틴마블  25    파일럿     미국  170   340,000,000


In [57]:
df.loc[:2, ['이름', '직업']]
df.loc[3:, '국적':'재산']

국적    키            재산
3  데미스키라  178           NaN
4     미국  270 1,000,000,000
5     미국  170   340,000,000
6    러시아  170    50,000,000

### dataframe의 팬시인덱싱

In [67]:
df[(df['나이'] > 30) & (df['나이'] < 50)]

이름  나이     직업     국적    키            재산
1     토르  45      신  아스가르드  190           NaN
4     헐크  33  핵물리학자     미국  270 1,000,000,000
6  블랙위도우  32    스파이    러시아  170    50,000,000

In [71]:
# df['키'] >= 180
df.loc[df['키'] >= 180, ['이름', '나이']]

이름  나이
1  토르  45
4  헐크  33

### dataframe 의 새 column 생성 및 drop

In [74]:
df['전투력'] = 98
print(df)
print()

df['전투력'] -= 5
print(df)
print()

# drop된 결과물만 확인하는것. 원본에는 적용 안됨
df.drop(columns=['전투력'])
print(df)
print()

# inplace=True 로 원본에 적용됨
df.drop(columns=['전투력'], inplace=True)
print(df)
print()

      이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   98
1     토르  45      신  아스가르드  190                NaN   98
2  스파이더맨  18   고등학생     미국  177                600   98
3   원더우먼  27     공주  데미스키라  178                NaN   98
4     헐크  33  핵물리학자     미국  270      1,000,000,000   98
5   캡틴마블  25    파일럿     미국  170        340,000,000   98
6  블랙위도우  32    스파이    러시아  170         50,000,000   98

      이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000,000   93
1     토르  45      신  아스가르드  190                NaN   93
2  스파이더맨  18   고등학생     미국  177                600   93
3   원더우먼  27     공주  데미스키라  178                NaN   93
4     헐크  33  핵물리학자     미국  270      1,000,000,000   93
5   캡틴마블  25    파일럿     미국  170        340,000,000   93
6  블랙위도우  32    스파이    러시아  170         50,000,000   93

      이름  나이     직업     국적    키                 재산  전투력
0   아이언맨  58    CEO     미국  174 11,500,000,000

### dataframe의 결측치 확인 및 처리

##### 결측치 확인

In [79]:
print(df['재산'].isnull())
print()
print(df[df['재산'].isnull()])
print()
print(df.isnull().sum())

0    False
1     True
2    False
3     True
4    False
5    False
6    False
Name: 재산, dtype: bool

     이름  나이  직업     국적    키  재산
1    토르  45   신  아스가르드  190 NaN
3  원더우먼  27  공주  데미스키라  178 NaN

이름    0
나이    0
직업    0
국적    0
키     0
재산    2
dtype: int64


##### 결측치 제거 (inplace=True 해야 원본에 적용)

In [81]:
print(df.dropna())

      이름  나이     직업   국적    키                 재산
0   아이언맨  58    CEO   미국  174 11,500,000,000,000
2  스파이더맨  18   고등학생   미국  177                600
4     헐크  33  핵물리학자   미국  270      1,000,000,000
5   캡틴마블  25    파일럿   미국  170        340,000,000
6  블랙위도우  32    스파이  러시아  170         50,000,000


##### 결측치 처리 (채우기) (inplace=True 해야 원본에 적용)

In [87]:
# nan을 0값으로 채우기
print(df['재산'].fillna(0))

# 평균값으로 채우기
print(df['재산'].fillna(df['재산'].mean()))
# print(df['재산'].fillna(df['재산'].mean(), inplace=True))

# 이전 값으로 채우기
print(df['재산'].ffill())

0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64
0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64
0   11,500,000,000,000
1    2,300,278,000,120
2                  600
3    2,300,278,000,120
4        1,000,000,000
5          340,000,000
6           50,000,000
Name: 재산, dtype: float64


### 미션 - 결측치 채워보기

In [97]:
df.iloc[5, 1] = np.nan
print(df)
print()
print(df['나이'].fillna(df['나이'].mean(), inplace=True))
print(df)

      이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블 NaN    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000

None
      이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  36    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000


C:\Users\EL91\AppData\Local\Temp\ipykernel_17036\3907626944.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df['나이'].fillna(df['나이'].mean(), inplace=True))


### 미션 - apply() 로 데이터에 함수 적용시키기

In [143]:
df = pd.read_csv('data\heroes.csv')

print(df)

      이름  나이     직업     국적    키                 재산
0   아이언맨  58    CEO     미국  174 11,500,000,000,000
1     토르  45      신  아스가르드  190                NaN
2  스파이더맨  18   고등학생     미국  177                600
3   원더우먼  27     공주  데미스키라  178                NaN
4     헐크  33  핵물리학자     미국  270      1,000,000,000
5   캡틴마블  25    파일럿     미국  170        340,000,000
6  블랙위도우  32    스파이    러시아  170         50,000,000


In [144]:
def add_cm(height) :
    return str(height) + 'cm'

df['키'] = df['키'].apply(add_cm)

print(df)

      이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174cm 11,500,000,000,000
1     토르  45      신  아스가르드  190cm                NaN
2  스파이더맨  18   고등학생     미국  177cm                600
3   원더우먼  27     공주  데미스키라  178cm                NaN
4     헐크  33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블  25    파일럿     미국  170cm        340,000,000
6  블랙위도우  32    스파이    러시아  170cm         50,000,000


In [101]:
df

이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174cm 11,500,000,000,000
1     토르  45      신  아스가르드  190cm  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177cm                600
3   원더우먼  27     공주  데미스키라  178cm  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블  36    파일럿     미국  170cm        340,000,000
6  블랙위도우  32    스파이    러시아  170cm         50,000,000

<hr>

### 나혼자 궁금증이 있어서 혼자 해보기

##### 급 내 질문

##### 데이터프레임에서 결측치를 nan으로 다루셨는데, '이름' 이나 '직업' 처럼 오브젝트 형식인 문자열로 된 컬럼의 데이터는 애초에 형식이 not a number 인데 이런 컬럼들도 결측치를 nan으로 처리하나요?

##### 만약 nan이 아니라 None 같은 형식으로 처리된다면, 아까 df.fillna() 같은 함수 적용시에는 None값은 건너뛰고 nan값 결측치에만 처리가 되는건가요? (아니면 None값에 숫자데이터가 문자열로 저장되는 형식?)
<br>

##### - 강사님 답

##### pandas기준, 일단 결측치는 문자열이건 숫자건 nan으로 표현됨. None값이 있을 수 있지만 이것도 nan으로 취급됨. nan 이 not a number 라서 헷갈릴만한데 판정은 이렇다고 하심.

##### 그래서 이 문자열 컬럼의 nan값도 fillna() 랑 ffill() 에 영향을 받는다고 하심


##### + 내가 추가로 직접 해보니, 문자열 데이터 컬럼 (오브젝트 형식) 에 fillna()로 float값을 넣었더니,
##### float 값이 그대로 들어감 (dtype으로 확인해봐도 그대로 float으로 저장된 채 들어있음)

##### 이 상태에서 info 를 해보니 해당 문자열 컬럼은 그대로 오브젝트 형식인데, 오브젝트 형식이 숫자형식까지 포괄하는 좀더 큰 형태의 데이터타입인듯

In [132]:
# 현상태 출력
df

이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174cm 11,500,000,000,000
1     토르  45      신  아스가르드  190cm  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177cm                600
3   원더우먼  27     공주  데미스키라  178cm  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블  36    파일럿     미국  170cm        340,000,000
6  블랙위도우  32    스파이    러시아  170cm         50,000,000

In [137]:
# '스파이더맨' 값 자리 비우기 (이름)
# df.iloc[2, 0] = np.nan

# print(df)
# print()

# '스파이더맨' 값 자리에 float 형식인 나이값 평균 (35.5) 기입
# print(df['이름'].fillna(df['나이'].mean(), inplace=True))
# '스파이더맨' 값 살리기
# print(df['이름'].fillna('스파이더맨', inplace=True))

# print(df)
# print()

# '스파이더맨' 값 자리에 기입된 데이터 타입 출력 (해당하는 데이터가 object 형식(str)일 시 error 출력)
# print(df.iloc[2, 0].dtype)


# ----------


# '18' 값 자리 비우기 (나이)
df.iloc[2, 1] = np.nan

print(df)
print()

# '18' 값 자리에 '테스트' 문자열 기입
# print(df['나이'].fillna('테스트', inplace=True))
# '18' 값 살리기
print(df['나이'].fillna(18, inplace=True))

print(df)
print()

# '18' 값 자리에 기입된 데이터 타입 출력 (해당하는 데이터가 object 형식(str)일 시 error 출력)
print(df.iloc[2, 1].dtype)

      이름   나이     직업     국적      키                 재산
0   아이언맨   58    CEO     미국  174cm 11,500,000,000,000
1     토르   45      신  아스가르드  190cm  2,300,278,000,120
2  스파이더맨  NaN   고등학생     미국  177cm                600
3   원더우먼   27     공주  데미스키라  178cm  2,300,278,000,120
4     헐크   33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블   36    파일럿     미국  170cm        340,000,000
6  블랙위도우   32    스파이    러시아  170cm         50,000,000

None
      이름  나이     직업     국적      키                 재산
0   아이언맨  58    CEO     미국  174cm 11,500,000,000,000
1     토르  45      신  아스가르드  190cm  2,300,278,000,120
2  스파이더맨  18   고등학생     미국  177cm                600
3   원더우먼  27     공주  데미스키라  178cm  2,300,278,000,120
4     헐크  33  핵물리학자     미국  270cm      1,000,000,000
5   캡틴마블  36    파일럿     미국  170cm        340,000,000
6  블랙위도우  32    스파이    러시아  170cm         50,000,000

float64


C:\Users\EL91\AppData\Local\Temp\ipykernel_17036\3219056132.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  print(df['나이'].fillna(18, inplace=True))
C:\Users\EL91\AppData\Local\Temp\ipykernel_17036\3219056132.py:31: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  print(df['나이'].fillna(18, inplace=True))


In [ ]:
# 문자열 타입 컬럼에 실수형 데이터 기입 후 info 출력
print(df.info())

# 기존 나이 column -> dtype == float64
# 나이 column에 '테스트' 문자열 기입 후 -> dtype == object

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   이름      7 non-null      object 
 1   나이      7 non-null      object 
 2   직업      7 non-null      object 
 3   국적      7 non-null      object 
 4   키       7 non-null      object 
 5   재산      7 non-null      float64
dtypes: float64(1), object(5)
memory usage: 468.0+ bytes
None


<hr>

### dataframe의 groupby

In [138]:
print(df.groupby('국적')['나이'].mean())

국적
데미스키라   27
러시아     32
미국      36
아스가르드   45
Name: 나이, dtype: float64


In [139]:
print(df.groupby('국적')['재산'].mean())

국적
데미스키라   2,300,278,000,120
러시아            50,000,000
미국      2,875,335,000,150
아스가르드   2,300,278,000,120
Name: 재산, dtype: float64
